export const countryCodes = [
  { code: "+1", label: "USA (+1)", iso: "us" },
  { code: "+7", label: "Russia (+7)", iso: "ru" },
  { code: "+20", label: "Egypt (+20)", iso: "eg" },
  { code: "+27", label: "South Africa (+27)", iso: "za" },
  { code: "+30", label: "Greece (+30)", iso: "gr" },
  { code: "+31", label: "Netherlands (+31)", iso: "nl" },
  { code: "+32", label: "Belgium (+32)", iso: "be" },
  { code: "+33", label: "France (+33)", iso: "fr" },
  { code: "+34", label: "Spain (+34)", iso: "es" },
  { code: "+36", label: "Hungary (+36)", iso: "hu" },
  { code: "+39", label: "Italy (+39)", iso: "it" },
  { code: "+40", label: "Romania (+40)", iso: "ro" },
  { code: "+41", label: "Switzerland (+41)", iso: "ch" },
  { code: "+43", label: "Austria (+43)", iso: "at" },
  { code: "+44", label: "UK (+44)", iso: "gb" },
  { code: "+45", label: "Denmark (+45)", iso: "dk" },
  { code: "+46", label: "Sweden (+46)", iso: "se" },
  { code: "+47", label: "Norway (+47)", iso: "no" },
  { code: "+48", label: "Poland (+48)", iso: "pl" },
  { code: "+49", label: "Germany (+49)", iso: "de" },
  { code: "+51", label: "Peru (+51)", iso: "pe" },
  { code: "+52", label: "Mexico (+52)", iso: "mx" },
  { code: "+53", label: "Cuba (+53)", iso: "cu" },
  { code: "+54", label: "Argentina (+54)", iso: "ar" },
  { code: "+55", label: "Brazil (+55)", iso: "br" },
  { code: "+56", label: "Chile (+56)", iso: "cl" },
  { code: "+57", label: "Colombia (+57)", iso: "co" },
  { code: "+58", label: "Venezuela (+58)", iso: "ve" },
  { code: "+60", label: "Malaysia (+60)", iso: "my" },
  { code: "+61", label: "Australia (+61)", iso: "au" },
  { code: "+62", label: "Indonesia (+62)", iso: "id" },
  { code: "+63", label: "Philippines (+63)", iso: "ph" },
  { code: "+64", label: "New Zealand (+64)", iso: "nz" },
  { code: "+65", label: "Singapore (+65)", iso: "sg" },
  { code: "+66", label: "Thailand (+66)", iso: "th" },
  { code: "+81", label: "Japan (+81)", iso: "jp" },
  { code: "+82", label: "South Korea (+82)", iso: "kr" },
  { code: "+84", label: "Vietnam (+84)", iso: "vn" },
  { code: "+86", label: "China (+86)", iso: "cn" },
  { code: "+90", label: "Turkey (+90)", iso: "tr" },
  { code: "+91", label: "India (+91)", iso: "in" },
  { code: "+92", label: "Pakistan (+92)", iso: "pk" },
  { code: "+93", label: "Afghanistan (+93)", iso: "af" },
  { code: "+94", label: "Sri Lanka (+94)", iso: "lk" },
  { code: "+95", label: "Myanmar (+95)", iso: "mm" },
  { code: "+98", label: "Iran (+98)", iso: "ir" },
  { code: "+211", label: "South Sudan (+211)", iso: "ss" },
  { code: "+212", label: "Morocco (+212)", iso: "ma" },
  { code: "+213", label: "Algeria (+213)", iso: "dz" },
  { code: "+216", label: "Tunisia (+216)", iso: "tn" },
  { code: "+218", label: "Libya (+218)", iso: "ly" },
  { code: "+220", label: "Gambia (+220)", iso: "gm" },
  { code: "+221", label: "Senegal (+221)", iso: "sn" },
  { code: "+222", label: "Mauritania (+222)", iso: "mr" },
  { code: "+223", label: "Mali (+223)", iso: "ml" },
  { code: "+224", label: "Guinea (+224)", iso: "gn" },
  { code: "+225", label: "Ivory Coast (+225)", iso: "ci" },
  { code: "+226", label: "Burkina Faso (+226)", iso: "bf" },
  { code: "+227", label: "Niger (+227)", iso: "ne" },
  { code: "+228", label: "Togo (+228)", iso: "tg" },
  { code: "+229", label: "Benin (+229)", iso: "bj" },
  { code: "+230", label: "Mauritius (+230)", iso: "mu" },
  { code: "+231", label: "Liberia (+231)", iso: "lr" },
  { code: "+232", label: "Sierra Leone (+232)", iso: "sl" },
  { code: "+233", label: "Ghana (+233)", iso: "gh" },
  { code: "+234", label: "Nigeria (+234)", iso: "ng" },
  { code: "+235", label: "Chad (+235)", iso: "td" },
  { code: "+236", label: "Central African Rep. (+236)", iso: "cf" },
  { code: "+237", label: "Cameroon (+237)", iso: "cm" },
  { code: "+238", label: "Cape Verde (+238)", iso: "cv" },
  { code: "+239", label: "Sao Tome & Principe (+239)", iso: "st" },
  { code: "+240", label: "Equatorial Guinea (+240)", iso: "gq" },
  { code: "+241", label: "Gabon (+241)", iso: "ga" },
  { code: "+242", label: "Congo (+242)", iso: "cg" },
  { code: "+243", label: "DR Congo (+243)", iso: "cd" },
  { code: "+244", label: "Angola (+244)", iso: "ao" },
  { code: "+245", label: "Guinea-Bissau (+245)", iso: "gw" },
  { code: "+246", label: "BIOT (+246)", iso: "io" },
  { code: "+248", label: "Seychelles (+248)", iso: "sc" },
  { code: "+249", label: "Sudan (+249)", iso: "sd" },
  { code: "+250", label: "Rwanda (+250)", iso: "rw" },
  { code: "+251", label: "Ethiopia (+251)", iso: "et" },
  { code: "+252", label: "Somalia (+252)", iso: "so" },
  { code: "+253", label: "Djibouti (+253)", iso: "dj" },
  { code: "+254", label: "Kenya (+254)", iso: "ke" },
  { code: "+255", label: "Tanzania (+255)", iso: "tz" },
  { code: "+256", label: "Uganda (+256)", iso: "ug" },
  { code: "+257", label: "Burundi (+257)", iso: "bi" },
  { code: "+258", label: "Mozambique (+258)", iso: "mz" },
  { code: "+260", label: "Zambia (+260)", iso: "zm" },
  { code: "+261", label: "Madagascar (+261)", iso: "mg" },
  { code: "+262", label: "Reunion (+262)", iso: "re" },
  { code: "+263", label: "Zimbabwe (+263)", iso: "zw" },
  { code: "+264", label: "Namibia (+264)", iso: "na" },
  { code: "+265", label: "Malawi (+265)", iso: "mw" },
  { code: "+266", label: "Lesotho (+266)", iso: "ls" },
  { code: "+267", label: "Botswana (+267)", iso: "bw" },
  { code: "+268", label: "Eswatini (+268)", iso: "sz" },
  { code: "+269", label: "Comoros (+269)", iso: "km" },
  { code: "+290", label: "St. Helena (+290)", iso: "sh" },
  { code: "+291", label: "Eritrea (+291)", iso: "er" },
  { code: "+297", label: "Aruba (+297)", iso: "aw" },
  { code: "+298", label: "Faroe Islands (+298)", iso: "fo" },
  { code: "+299", label: "Greenland (+299)", iso: "gl" },
  { code: "+350", label: "Gibraltar (+350)", iso: "gi" },
  { code: "+351", label: "Portugal (+351)", iso: "pt" },
  { code: "+352", label: "Luxembourg (+352)", iso: "lu" },
  { code: "+353", label: "Ireland (+353)", iso: "ie" },
  { code: "+354", label: "Iceland (+354)", iso: "is" },
  { code: "+355", label: "Albania (+355)", iso: "al" },
  { code: "+356", label: "Malta (+356)", iso: "mt" },
  { code: "+357", label: "Cyprus (+357)", iso: "cy" },
  { code: "+358", label: "Finland (+358)", iso: "fi" },
  { code: "+359", label: "Bulgaria (+359)", iso: "bg" },
  { code: "+370", label: "Lithuania (+370)", iso: "lt" },
  { code: "+371", label: "Latvia (+371)", iso: "lv" },
  { code: "+372", label: "Estonia (+372)", iso: "ee" },
  { code: "+373", label: "Moldova (+373)", iso: "md" },
  { code: "+374", label: "Armenia (+374)", iso: "am" },
  { code: "+375", label: "Belarus (+375)", iso: "by" },
  { code: "+376", label: "Andorra (+376)", iso: "ad" },
  { code: "+377", label: "Monaco (+377)", iso: "mc" },
  { code: "+378", label: "San Marino (+378)", iso: "sm" },
  { code: "+380", label: "Ukraine (+380)", iso: "ua" },
  { code: "+381", label: "Serbia (+381)", iso: "rs" },
  { code: "+382", label: "Montenegro (+382)", iso: "me" },
  { code: "+383", label: "Kosovo (+383)", iso: "xk" },
  { code: "+385", label: "Croatia (+385)", iso: "hr" },
  { code: "+386", label: "Slovenia (+386)", iso: "si" },
  { code: "+387", label: "Bosnia (+387)", iso: "ba" },
  { code: "+389", label: "North Macedonia (+389)", iso: "mk" },
  { code: "+420", label: "Czech Rep. (+420)", iso: "cz" },
  { code: "+421", label: "Slovakia (+421)", iso: "sk" },
  { code: "+423", label: "Liechtenstein (+423)", iso: "li" },
  { code: "+500", label: "Falkland Islands (+500)", iso: "fk" },
  { code: "+501", label: "Belize (+501)", iso: "bz" },
  { code: "+502", label: "Guatemala (+502)", iso: "gt" },
  { code: "+503", label: "El Salvador (+503)", iso: "sv" },
  { code: "+504", label: "Honduras (+504)", iso: "hn" },
  { code: "+505", label: "Nicaragua (+505)", iso: "ni" },
  { code: "+506", label: "Costa Rica (+506)", iso: "cr" },
  { code: "+507", label: "Panama (+507)", iso: "pa" },
  { code: "+508", label: "St. Pierre & Miquelon (+508)", iso: "pm" },
  { code: "+509", label: "Haiti (+509)", iso: "ht" },
  { code: "+590", label: "Guadeloupe (+590)", iso: "gp" },
  { code: "+591", label: "Bolivia (+591)", iso: "bo" },
  { code: "+592", label: "Guyana (+592)", iso: "gy" },
  { code: "+593", label: "Ecuador (+593)", iso: "ec" },
  { code: "+594", label: "French Guiana (+594)", iso: "gf" },
  { code: "+595", label: "Paraguay (+595)", iso: "py" },
  { code: "+596", label: "Martinique (+596)", iso: "mq" },
  { code: "+597", label: "Suriname (+597)", iso: "sr" },
  { code: "+598", label: "Uruguay (+598)", iso: "uy" },
  { code: "+599", label: "Caribbean Netherlands (+599)", iso: "bq" },
  { code: "+670", label: "Timor-Leste (+670)", iso: "tl" },
  { code: "+672", label: "Antarctica (+672)", iso: "aq" },
  { code: "+673", label: "Brunei (+673)", iso: "bn" },
  { code: "+674", label: "Nauru (+674)", iso: "nr" },
  { code: "+675", label: "Papua New Guinea (+675)", iso: "pg" },
  { code: "+676", label: "Tonga (+676)", iso: "to" },
  { code: "+677", label: "Solomon Islands (+677)", iso: "sb" },
  { code: "+678", label: "Vanuatu (+678)", iso: "vu" },
  { code: "+679", label: "Fiji (+679)", iso: "fj" },
  { code: "+680", label: "Palau (+680)", iso: "pw" },
  { code: "+681", label: "Wallis & Futuna (+681)", iso: "wf" },
  { code: "+682", label: "Cook Islands (+682)", iso: "ck" },
  { code: "+683", label: "Niue (+683)", iso: "nu" },
  { code: "+685", label: "Samoa (+685)", iso: "ws" },
  { code: "+686", label: "Kiribati (+686)", iso: "ki" },
  { code: "+687", label: "New Caledonia (+687)", iso: "nc" },
  { code: "+688", label: "Tuvalu (+688)", iso: "tv" },
  { code: "+689", label: "French Polynesia (+689)", iso: "pf" },
  { code: "+690", label: "Tokelau (+690)", iso: "tk" },
  { code: "+691", label: "Micronesia (+691)", iso: "fm" },
  { code: "+692", label: "Marshall Islands (+692)", iso: "mh" },
  { code: "+880", label: "Bangladesh (+880)", iso: "bd" },
  { code: "+886", label: "Taiwan (+886)", iso: "tw" },
  { code: "+960", label: "Maldives (+960)", iso: "mv" },
  { code: "+961", label: "Lebanon (+961)", iso: "lb" },
  { code: "+962", label: "Jordan (+962)", iso: "jo" },
  { code: "+963", label: "Syria (+963)", iso: "sy" },
  { code: "+964", label: "Iraq (+964)", iso: "iq" },
  { code: "+965", label: "Kuwait (+965)", iso: "kw" },
  { code: "+966", label: "Saudi Arabia (+966)", iso: "sa" },
  { code: "+967", label: "Yemen (+967)", iso: "ye" },
  { code: "+968", label: "Oman (+968)", iso: "om" },
  { code: "+970", label: "Palestine (+970)", iso: "ps" },
  { code: "+971", label: "UAE (+971)", iso: "ae" },
  { code: "+972", label: "Israel (+972)", iso: "il" },
  { code: "+973", label: "Bahrain (+973)", iso: "bh" },
  { code: "+974", label: "Qatar (+974)", iso: "qa" },
  { code: "+975", label: "Bhutan (+975)", iso: "bt" },
  { code: "+976", label: "Mongolia (+976)", iso: "mn" },
  { code: "+977", label: "Nepal (+977)", iso: "np" }
];